Refactor + create and delete template and project - frontend + backend
SavenkoRodion/printing-managment-system pull request #33
Opened 2024-11-11 15:39 UTC by icewuuu

2024-11-12 11:38 UTC, Adriansmola approved these changes

2024-11-12 22:17 UTC, SavenkoRodion requested changes
PR nie gotowy do merge. To jest review części backendowej

2024-11-13 20:47 UTC, SavenkoRodion requested changes
Częściowe review UI

2024-11-21 19:00 UTC, SavenkoRodion approved these changes

2024-11-25 14:25 UTC, merged